# Generated by Django 4.0.5 on 2022-06-21 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producing_country', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('country_images', models.ImageField(blank=True, null=True, upload_to='image')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': "Country's",
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('brand_images', models.ImageField(blank=True, null=True, upload_to='brand')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Brand_car',
                'verbose_name_plural': "Brand_car's",
            },
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('equpment', models.CharField(choices=[('not_choice', 'Комплектация не выбрана'), ('basic', 'Базовая'), ('average', 'Средняя'), ('maximum', 'Максимальная')], default='not_choice', max_length=10)),
                ('years', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.brand', verbose_name='Brand')),
            ],
            options={
                'verbose_name': 'Auto',
                'verbose_name_plural': 'Auto',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_paid', 'Не просмотрено'), ('paid', 'Просмотрено')], default='not_paid', max_length=10)),
                ('color', models.CharField(choices=[('no_color', 'Цвет не выбран'), ('black', 'Черный'), ('red', 'Красный'), ('metal', 'Металлик'), ('white', 'Белый'), ('yellow', 'Желтый')], default='no_color', max_length=10, verbose_name='Цвет')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата когда нужен автомобиль')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='main.auto')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
                'unique_together': {('product', 'order')},
            },
        ),
    ]
