# Generated by Django 4.0.5 on 2022-06-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='created_at',
            field=models.DateTimeField(verbose_name='Дата когда нужен автомобиль'),
        ),
    ]
