# Generated by Django 4.0.5 on 2022-06-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_orderitems_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
