# Generated by Django 4.0.5 on 2022-06-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_orderitems_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='auto_images',
            field=models.ImageField(blank=True, null=True, upload_to='models'),
        ),
    ]
