# Generated by Django 4.0.5 on 2022-06-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.CharField(max_length=255, verbose_name='Ф.И.О'),
        ),
    ]
