# Generated by Django 4.0.5 on 2022-06-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_auto_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='years',
            field=models.IntegerField(max_length=20),
        ),
    ]
