# Generated by Django 4.0.5 on 2022-06-25 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_review_model_alter_auto_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='model',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='main.auto'),
        ),
    ]
