# Generated by Django 4.0.5 on 2022-06-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_review_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='years',
            field=models.PositiveIntegerField(),
        ),
    ]
